function getRequiredElement<TElement extends Element>(id: string): TElement {
  const element = document.getElementById(id);
  if (!element) {
    throw new Error(`Missing required DOM element #${id}`);
  }

  return element as unknown as TElement;
}

export interface AppElements {
  appFooter: HTMLElement;
  authPanel: HTMLElement;
  authSummary: HTMLElement;
  authSectionTitle: HTMLElement;
  authStepEyebrow: HTMLElement;
  backToPlannerLink: HTMLAnchorElement;
  controlsSectionTitle: HTMLElement;
  controlsStepEyebrow: HTMLElement;
  creditsHero: HTMLElement;
  creditsHeroEyebrow: HTMLElement;
  creditsHeroLede: HTMLElement;
  creditsHeroTitle: HTMLElement;
  creditsPage: HTMLElement;
  creditsPanelEyebrow: HTMLElement;
  creditsPanelTitle: HTMLElement;
  creditsSections: HTMLElement;
  currentLocationButton: HTMLButtonElement;
  demoButton: HTMLButtonElement;
  detourInput: HTMLInputElement;
  detourLabel: HTMLElement;
  distanceLabel: HTMLElement;
  distanceValue: HTMLElement;
  emailInput: HTMLInputElement;
  emailLabel: HTMLElement;
  endInput: HTMLSelectElement;
  endStationLabel: HTMLElement;
  finishTimeInput: HTMLInputElement;
  finishTimeLabel: HTMLElement;
  finishTimeNote: HTMLElement;
  footerBrandName: HTMLElement;
  footerCreditsLink: HTMLAnchorElement;
  languageLabel: HTMLElement;
  languageSelect: HTMLSelectElement;
  legendEmpty: HTMLElement;
  legendOccupied: HTMLElement;
  legendRoute: HTMLElement;
  loadLiveButton: HTMLButtonElement;
  loginButton: HTMLButtonElement;
  loginForm: HTMLFormElement;
  logoutButton: HTMLButtonElement;
  networkAttribution: HTMLElement;
  networkEyebrow: HTMLElement;
  networkSectionTitle: HTMLElement;
  networkSvg: SVGSVGElement;
  networkTooltip: HTMLElement;
  overheadInput: HTMLInputElement;
  overheadLabel: HTMLElement;
  passwordInput: HTMLInputElement;
  passwordLabel: HTMLElement;
  planButton: HTMLButtonElement;
  plannerEyebrow: HTMLElement;
  plannerHero: HTMLElement;
  plannerLedeText: HTMLElement;
  plannerNote: HTMLElement;
  plannerPage: HTMLElement;
  plannerTitle: HTMLElement;
  plannerWhatIsThisLink: HTMLAnchorElement;
  pointsLabel: HTMLElement;
  pointsValue: HTMLElement;
  ridesLabel: HTMLElement;
  ridesValue: HTMLElement;
  rideTimeLabel: HTMLElement;
  routeEyebrow: HTMLElement;
  routeLinks: HTMLAnchorElement[];
  routeList: HTMLElement;
  routeSectionTitle: HTMLElement;
  rememberEmailCheckbox: HTMLInputElement;
  rememberEmailLabel: HTMLElement;
  sessionLabel: HTMLElement;
  sessionStatus: HTMLElement;
  snapshotDisclosureSummary: HTMLElement;
  snapshotLabel: HTMLElement;
  snapshotSource: HTMLElement;
  speedInput: HTMLInputElement;
  speedLabel: HTMLElement;
  startInput: HTMLSelectElement;
  startStationLabel: HTMLElement;
  stationCount: HTMLElement;
  stationsLabel: HTMLElement;
  statsAnonymousBreakdown: HTMLElement;
  statsAnonymousTitle: HTMLElement;
  statsBackToPlannerLink: HTMLAnchorElement;
  statsHero: HTMLElement;
  statsHeroEyebrow: HTMLElement;
  statsHeroLede: HTMLElement;
  statsHeroTitle: HTMLElement;
  statsLanguageGrid: HTMLElement;
  statsLanguageTitle: HTMLElement;
  statsLastUpdated: HTMLElement;
  statsPage: HTMLElement;
  statsPanelEyebrow: HTMLElement;
  statsPanelTitle: HTMLElement;
  statsSignedInBreakdown: HTMLElement;
  statsSignedInTitle: HTMLElement;
  statsSummaryGrid: HTMLElement;
  statsTopEventsList: HTMLElement;
  statsTopEventsTitle: HTMLElement;
  summaryDetails: HTMLElement;
  summarySectionTitle: HTMLElement;
  summaryStepEyebrow: HTMLElement;
  timeValue: HTMLElement;
  toast: HTMLElement;
  footerStatsLink: HTMLAnchorElement;
}

export function getAppElements(): AppElements {
  return {
    appFooter: getRequiredElement<HTMLElement>("appFooter"),
    authPanel: getRequiredElement<HTMLElement>("authPanel"),
    authSummary: getRequiredElement<HTMLElement>("authSummary"),
    authSectionTitle: getRequiredElement<HTMLElement>("authSectionTitle"),
    authStepEyebrow: getRequiredElement<HTMLElement>("authStepEyebrow"),
    backToPlannerLink: getRequiredElement<HTMLAnchorElement>("backToPlannerLink"),
    controlsSectionTitle: getRequiredElement<HTMLElement>("controlsSectionTitle"),
    controlsStepEyebrow: getRequiredElement<HTMLElement>("controlsStepEyebrow"),
    creditsHero: getRequiredElement<HTMLElement>("creditsHero"),
    creditsHeroEyebrow: getRequiredElement<HTMLElement>("creditsHeroEyebrow"),
    creditsHeroLede: getRequiredElement<HTMLElement>("creditsHeroLede"),
    creditsHeroTitle: getRequiredElement<HTMLElement>("creditsHeroTitle"),
    creditsPage: getRequiredElement<HTMLElement>("creditsPage"),
    creditsPanelEyebrow: getRequiredElement<HTMLElement>("creditsPanelEyebrow"),
    creditsPanelTitle: getRequiredElement<HTMLElement>("creditsPanelTitle"),
    creditsSections: getRequiredElement<HTMLElement>("creditsSections"),
    currentLocationButton: getRequiredElement<HTMLButtonElement>("currentLocationButton"),
    demoButton: getRequiredElement<HTMLButtonElement>("demoButton"),
    detourInput: getRequiredElement<HTMLInputElement>("detourInput"),
    detourLabel: getRequiredElement<HTMLElement>("detourLabel"),
    distanceLabel: getRequiredElement<HTMLElement>("distanceLabel"),
    distanceValue: getRequiredElement<HTMLElement>("distanceValue"),
    emailInput: getRequiredElement<HTMLInputElement>("emailInput"),
    emailLabel: getRequiredElement<HTMLElement>("emailLabel"),
    endInput: getRequiredElement<HTMLSelectElement>("endInput"),
    endStationLabel: getRequiredElement<HTMLElement>("endStationLabel"),
    finishTimeInput: getRequiredElement<HTMLInputElement>("finishTimeInput"),
    finishTimeLabel: getRequiredElement<HTMLElement>("finishTimeLabel"),
    finishTimeNote: getRequiredElement<HTMLElement>("finishTimeNote"),
    footerBrandName: getRequiredElement<HTMLElement>("footerBrandName"),
    footerCreditsLink: getRequiredElement<HTMLAnchorElement>("footerCreditsLink"),
    languageLabel: getRequiredElement<HTMLElement>("languageLabel"),
    languageSelect: getRequiredElement<HTMLSelectElement>("languageSelect"),
    legendEmpty: getRequiredElement<HTMLElement>("legendEmpty"),
    legendOccupied: getRequiredElement<HTMLElement>("legendOccupied"),
    legendRoute: getRequiredElement<HTMLElement>("legendRoute"),
    loadLiveButton: getRequiredElement<HTMLButtonElement>("loadLiveButton"),
    loginButton: getRequiredElement<HTMLButtonElement>("loginButton"),
    loginForm: getRequiredElement<HTMLFormElement>("loginForm"),
    logoutButton: getRequiredElement<HTMLButtonElement>("logoutButton"),
    networkAttribution: getRequiredElement<HTMLElement>("networkAttribution"),
    networkEyebrow: getRequiredElement<HTMLElement>("networkEyebrow"),
    networkSectionTitle: getRequiredElement<HTMLElement>("networkSectionTitle"),
    networkSvg: getRequiredElement<SVGSVGElement>("networkSvg"),
    networkTooltip: getRequiredElement<HTMLElement>("networkTooltip"),
    overheadInput: getRequiredElement<HTMLInputElement>("overheadInput"),
    overheadLabel: getRequiredElement<HTMLElement>("overheadLabel"),
    passwordInput: getRequiredElement<HTMLInputElement>("passwordInput"),
    passwordLabel: getRequiredElement<HTMLElement>("passwordLabel"),
    planButton: getRequiredElement<HTMLButtonElement>("planButton"),
    plannerEyebrow: getRequiredElement<HTMLElement>("plannerEyebrow"),
    plannerHero: getRequiredElement<HTMLElement>("plannerHero"),
    plannerLedeText: getRequiredElement<HTMLElement>("plannerLedeText"),
    plannerNote: getRequiredElement<HTMLElement>("plannerNote"),
    plannerPage: getRequiredElement<HTMLElement>("plannerPage"),
    plannerTitle: getRequiredElement<HTMLElement>("plannerTitle"),
    plannerWhatIsThisLink: getRequiredElement<HTMLAnchorElement>("plannerWhatIsThisLink"),
    pointsLabel: getRequiredElement<HTMLElement>("pointsLabel"),
    pointsValue: getRequiredElement<HTMLElement>("pointsValue"),
    ridesLabel: getRequiredElement<HTMLElement>("ridesLabel"),
    ridesValue: getRequiredElement<HTMLElement>("ridesValue"),
    rideTimeLabel: getRequiredElement<HTMLElement>("rideTimeLabel"),
    routeEyebrow: getRequiredElement<HTMLElement>("routeEyebrow"),
    routeLinks: Array.from(document.querySelectorAll<HTMLAnchorElement>("[data-route]")),
    routeList: getRequiredElement<HTMLElement>("routeList"),
    routeSectionTitle: getRequiredElement<HTMLElement>("routeSectionTitle"),
    rememberEmailCheckbox: getRequiredElement<HTMLInputElement>("rememberEmailCheckbox"),
    rememberEmailLabel: getRequiredElement<HTMLElement>("rememberEmailLabel"),
    sessionLabel: getRequiredElement<HTMLElement>("sessionLabel"),
    sessionStatus: getRequiredElement<HTMLElement>("sessionStatus"),
    snapshotDisclosureSummary: getRequiredElement<HTMLElement>("snapshotDisclosureSummary"),
    snapshotLabel: getRequiredElement<HTMLElement>("snapshotLabel"),
    snapshotSource: getRequiredElement<HTMLElement>("snapshotSource"),
    speedInput: getRequiredElement<HTMLInputElement>("speedInput"),
    speedLabel: getRequiredElement<HTMLElement>("speedLabel"),
    startInput: getRequiredElement<HTMLSelectElement>("startInput"),
    startStationLabel: getRequiredElement<HTMLElement>("startStationLabel"),
    stationCount: getRequiredElement<HTMLElement>("stationCount"),
    stationsLabel: getRequiredElement<HTMLElement>("stationsLabel"),
    statsAnonymousBreakdown: getRequiredElement<HTMLElement>("statsAnonymousBreakdown"),
    statsAnonymousTitle: getRequiredElement<HTMLElement>("statsAnonymousTitle"),
    statsBackToPlannerLink: getRequiredElement<HTMLAnchorElement>("statsBackToPlannerLink"),
    statsHero: getRequiredElement<HTMLElement>("statsHero"),
    statsHeroEyebrow: getRequiredElement<HTMLElement>("statsHeroEyebrow"),
    statsHeroLede: getRequiredElement<HTMLElement>("statsHeroLede"),
    statsHeroTitle: getRequiredElement<HTMLElement>("statsHeroTitle"),
    statsLanguageGrid: getRequiredElement<HTMLElement>("statsLanguageGrid"),
    statsLanguageTitle: getRequiredElement<HTMLElement>("statsLanguageTitle"),
    statsLastUpdated: getRequiredElement<HTMLElement>("statsLastUpdated"),
    statsPage: getRequiredElement<HTMLElement>("statsPage"),
    statsPanelEyebrow: getRequiredElement<HTMLElement>("statsPanelEyebrow"),
    statsPanelTitle: getRequiredElement<HTMLElement>("statsPanelTitle"),
    statsSignedInBreakdown: getRequiredElement<HTMLElement>("statsSignedInBreakdown"),
    statsSignedInTitle: getRequiredElement<HTMLElement>("statsSignedInTitle"),
    statsSummaryGrid: getRequiredElement<HTMLElement>("statsSummaryGrid"),
    statsTopEventsList: getRequiredElement<HTMLElement>("statsTopEventsList"),
    statsTopEventsTitle: getRequiredElement<HTMLElement>("statsTopEventsTitle"),
    summaryDetails: getRequiredElement<HTMLElement>("summaryDetails"),
    summarySectionTitle: getRequiredElement<HTMLElement>("summarySectionTitle"),
    summaryStepEyebrow: getRequiredElement<HTMLElement>("summaryStepEyebrow"),
    timeValue: getRequiredElement<HTMLElement>("timeValue"),
    toast: getRequiredElement<HTMLElement>("toast"),
    footerStatsLink: getRequiredElement<HTMLAnchorElement>("footerStatsLink"),
  };
}
